--- table mit allen heldenfähigkeiten
Abilities = {
	AbilityBuildCannon = 3,
	AbilityCamouflage = 5,
	AbilityCircularAttack = 7,
	AbilityConvertBuildings = 9,
	AbilityConvertSettlers = 10,
	AbilityInflictFear = 8,
	AbilityMotivateWorkers = 17,
	AbilityPlaceBomb = 2,
	AbilityPlaceKeg = 16,
	AbilityRangedEffect = 6,
	AbilityScoutBinoculars = 11,
	AbilityScoutFindResources = 13,
	AbilityScoutTorches = 12,
	AbilitySendHawk = 1,
	AbilityShuriken = 15,
	AbilitySniper = 14,
	AbilitySummon = 4,
}
